// @ts-check
import js from '@eslint/js';
import prettier from 'eslint-config-prettier';
import importX from 'eslint-plugin-import-x';
import reactHooks from 'eslint-plugin-react-hooks';
import tseslint from 'typescript-eslint';

/**
 * Flat ESLint config for the whole workspace.
 *
 * Philosophy: the compiler catches type errors, Prettier catches formatting.
 * ESLint is reserved for what neither can see — architectural boundaries, unsafe
 * patterns, and the child-safety / privacy invariants in docs/CHILD_SAFETY.md
 * and PRIVACY.md.
 */
export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/build/**',
      '**/.next/**',
      '**/.expo/**',
      '**/coverage/**',
      '**/playwright-report/**',
      '**/test-results/**',
      '**/*.tsbuildinfo',
      '**/next-env.d.ts',
      '**/expo-env.d.ts',
      // Generated by `pnpm db:types`; its shape is the generator's concern.
      'packages/types/src/database.generated.ts',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,

  /* ---------- Type-aware rules for workspace TypeScript ---------- */
  {
    files: ['**/*.ts', '**/*.tsx'],
    ignores: ['**/*.config.ts'],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: { 'import-x': importX },
    rules: {
      /* ---------- Correctness ---------- */
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-unnecessary-condition': 'error',
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
      '@typescript-eslint/switch-exhaustiveness-check': 'error',
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      '@typescript-eslint/require-await': 'error',
      '@typescript-eslint/return-await': ['error', 'always'],
      '@typescript-eslint/no-unused-vars': [
        'error',
        // `_`-prefixed names are an explicit "deliberately discarded" marker,
        // most often when destructuring a field out of an object.
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
          ignoreRestSiblings: true,
        },
      ],
      '@typescript-eslint/restrict-template-expressions': [
        'error',
        { allowNumber: false, allowBoolean: false },
      ],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-param-reassign': ['error', { props: true }],

      /* ---------- Logging and PII (docs/LOGGING.md) ---------- */
      // Direct console writes bypass the redacting logger, which is the only
      // thing standing between a child's transcript and a log aggregator.
      'no-console': 'error',

      /* ---------- Unsafe primitives ---------- */
      'no-restricted-properties': [
        'error',
        {
          object: 'Math',
          property: 'random',
          message: 'Math.random() is not cryptographically secure. Use node:crypto.',
        },
      ],
      'no-restricted-syntax': [
        'error',
        {
          selector: "NewExpression[callee.name='Date'][arguments.length=0]",
          message:
            'Inject a Clock (see @kids/shared) instead of reading wall time directly — it makes tests deterministic.',
        },
      ],

      /* ---------- Import hygiene ----------
       * `no-extraneous-dependencies` carries real weight since ADR-0008: with a
       * hoisted node_modules it is what stops a package importing something it
       * never declared. It is an error, never a warning.
       */
      'import-x/no-extraneous-dependencies': 'error',
      'import-x/no-self-import': 'error',
      'import-x/order': [
        'error',
        {
          groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index'],
          'newlines-between': 'always',
          alphabetize: { order: 'asc', caseInsensitive: true },
        },
      ],
    },
  },

  /* ---------- Architectural boundaries: dependencies point inward ---------- */
  {
    files: ['packages/**/*.{ts,tsx}', 'services/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['@kids/api', '@kids/mobile', '@kids/web', '**/apps/**'],
              message:
                'Dependencies point inward: packages/ and services/ must never import from apps/.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['packages/types/**/*.ts'],
    rules: {
      // @kids/types must have no runtime dependencies, so React Native, the API,
      // and the web dashboard can all depend on it freely.
      //
      // The regex matches specifiers not starting with `.` — bare package
      // specifiers only. Relative imports stay allowed: the package may be
      // internally modular, it just may not reach outside itself.
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              regex: '^[^.]',
              message:
                '@kids/types must have no runtime dependencies. Declare types and const unions only.',
            },
          ],
        },
      ],
    },
  },

  /* ---------- Fastify plugins and routes ----------
   * Fastify's `FastifyPluginAsync` and route handler contracts require an async
   * signature whether or not the body awaits anything. `require-await` is right
   * everywhere else, so it is relaxed here rather than globally.
   */
  {
    files: ['apps/api/src/plugins/**/*.ts', 'apps/api/src/routes/**/*.ts', 'apps/api/src/app.ts'],
    rules: {
      '@typescript-eslint/require-await': 'off',
    },
  },

  /* ---------- Provider adapters ----------
   * An adapter implements an async port. Several of its methods have nothing to
   * await — the mock resolves immediately, and a real adapter's cheap paths do
   * too — but the signature is fixed by the interface. `require-await` is right
   * everywhere else, so it is relaxed here rather than globally.
   *
   * The mobile audio port is the same shape for the same reason: expo-audio's
   * playback calls are synchronous, while `AudioPort` is async because the
   * recording half genuinely is.
   */
  {
    files: [
      'services/*/src/*-provider.ts',
      'services/*/src/*-adapter.ts',
      'apps/mobile/src/hooks/*-port.ts',
    ],
    rules: {
      '@typescript-eslint/require-await': 'off',
    },
  },

  /* ---------- Decorative animation timing ----------
   * The 3D character rig's idle/talk loops (apps/mobile/src/three) use
   * Math.random() purely to jitter animation amplitude and duration so a
   * blink or a head-sway loop does not repeat identically forever — never for
   * anything security- or privacy-sensitive. node:crypto has no synchronous
   * API, which is what every one of these per-frame GSAP callbacks needs.
   */
  {
    files: ['apps/mobile/src/three/**/*.ts'],
    rules: {
      'no-restricted-properties': 'off',
    },
  },

  /* ---------- React surfaces ---------- */
  {
    files: ['apps/web/**/*.{ts,tsx}', 'apps/mobile/**/*.{ts,tsx}', 'packages/ui/**/*.{ts,tsx}'],
    plugins: { 'react-hooks': reactHooks },
    rules: {
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
    },
  },

  /* ---------- Tests may relax a few rules ---------- */
  {
    files: ['**/*.test.ts', '**/*.test.tsx', '**/*.spec.ts', 'tests/**/*.ts'],
    rules: {
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unnecessary-condition': 'off',
      'no-restricted-syntax': 'off',
      'import-x/no-extraneous-dependencies': 'off',
      // Test doubles implement async interfaces and mostly have nothing to
      // await. Enforcing it here produces `await Promise.resolve()` noise that
      // makes the stub harder to read than the thing it stands in for.
      '@typescript-eslint/require-await': 'off',
      '@typescript-eslint/return-await': 'off',
    },
  },

  /* ---------- Scripts and config files ----------
   * Not part of any tsconfig project, so type-aware linting cannot run on them.
   * Also not application code: writing to stdout is their job.
   */
  {
    files: ['**/*.mjs', '**/*.js', '**/*.cjs', '**/*.config.ts'],
    extends: [tseslint.configs.disableTypeChecked],
    languageOptions: {
      globals: {
        console: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        URL: 'readonly',
        module: 'writable',
        require: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
      },
    },
    rules: {
      'no-console': 'off',
      'import-x/no-extraneous-dependencies': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-require-imports': 'off',
    },
  },

  prettier,
);
