import buddy from '../../assets/audio/music-buddy-the-dog.wav';
import sky from '../../assets/audio/music-captain-sky.wav';
import zia from '../../assets/audio/music-captain-zia.wav';
import dada from '../../assets/audio/music-dada-jee.wav';
import lily from '../../assets/audio/music-lily-the-fairy.wav';
import mira from '../../assets/audio/music-mira-the-moon.wav';
import nano from '../../assets/audio/music-nano-the-robot.wav';
import pip from '../../assets/audio/music-pip-the-fox.wav';
import owl from '../../assets/audio/music-professor-owl.wav';
import { DEFAULT_CHARACTER, isCharacterSlug, type CharacterSlug } from '../theme/child-theme';

/**
 * Each character's own background music.
 *
 * Keyed by slug, and typed as a full `Record<CharacterSlug, …>` so adding a
 * character to the cast without giving it a tune is a compile error rather than
 * a silent fallback to the wrong one. The loops are generated by
 * `scripts/generate-music-loop.mjs`.
 */
const TRACKS: Readonly<Record<CharacterSlug, number>> = {
  'buddy-the-dog': buddy,
  'lily-the-fairy': lily,
  'captain-sky': sky,
  'professor-owl': owl,
  'pip-the-fox': pip,
  'nano-the-robot': nano,
  'mira-the-moon': mira,
  'captain-zia': zia,
  'dada-jee': dada,
};

/** The tune for a slug from the API or route; an unknown slug gets Buddy's. */
export const musicFor = (slug: string | undefined): number =>
  TRACKS[isCharacterSlug(slug) ? slug : DEFAULT_CHARACTER];
